// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QlChoThueNha1.Data;

#nullable disable

namespace QlChoThueNha1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260224143918_UpdateUser")]
    partial class UpdateUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HouseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HouseTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Phòng trọ giá rẻ, phù hợp sinh viên",
                            Name = "Phòng trọ"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Căn hộ chung cư hiện đại",
                            Name = "Chung cư"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Nhà riêng biệt, không gian rộng rãi",
                            Name = "Nhà nguyên căn"
                        });
                });

            modelBuilder.Entity("QlChoThueNha1.Models.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("HouseTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("HouseTypeId");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Lê Lợi, Quận 1, TP.HCM",
                            Area = 25.0,
                            Description = "Phòng trọ đẹp, gần chợ Bến Thành, đầy đủ tiện nghi",
                            HouseTypeId = 1,
                            ImageUrl = "/images/house1.jpg",
                            Name = "Phòng trọ Quận 1",
                            Price = 3000000m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 2,
                            Address = "45 Nguyễn Thị Minh Khai, Quận 3, TP.HCM",
                            Area = 60.0,
                            Description = "Căn hộ 2 phòng ngủ, view đẹp, an ninh tốt",
                            HouseTypeId = 2,
                            ImageUrl = "/images/house2.jpg",
                            Name = "Chung cư Quận 3",
                            Price = 8000000m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 3,
                            Address = "89 Huỳnh Tấn Phát, Quận 7, TP.HCM",
                            Area = 120.0,
                            Description = "Nhà 1 trệt 2 lầu, 4 phòng ngủ, có sân vườn",
                            HouseTypeId = 3,
                            ImageUrl = "/images/house3.jpg",
                            Name = "Nhà nguyên căn Quận 7",
                            Price = 15000000m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 4,
                            Address = "234 Điện Biên Phủ, Quận Bình Thạnh, TP.HCM",
                            Area = 20.0,
                            Description = "Gần trường đại học, tiện cho sinh viên",
                            HouseTypeId = 1,
                            ImageUrl = "/images/house4.jpg",
                            Name = "Phòng trọ Quận Bình Thạnh",
                            Price = 2500000m,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 5,
                            Address = "567 Mai Chí Thọ, Quận 2, TP.HCM",
                            Area = 80.0,
                            Description = "Căn hộ cao cấp, đầy đủ nội thất",
                            HouseTypeId = 2,
                            ImageUrl = "/images/house5.jpg",
                            Name = "Chung cư Quận 2",
                            Price = 12000000m,
                            Status = "Rented"
                        });
                });

            modelBuilder.Entity("QlChoThueNha1.Models.RentalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.HasIndex("UserId");

                    b.ToTable("RentalRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HouseId = 5,
                            Note = "Thuê dài hạn 1 năm",
                            RequestDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("QlChoThueNha1.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@gmail.com",
                            FullName = "Quản trị viên",
                            Password = "123456",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "customer1@gmail.com",
                            FullName = "Nguyễn Văn A",
                            Password = "123456",
                            Role = "Customer",
                            Username = "customer1"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "customer2@gmail.com",
                            FullName = "Trần Thị B",
                            Password = "123456",
                            Role = "Customer",
                            Username = "customer2"
                        });
                });

            modelBuilder.Entity("QlChoThueNha1.Models.House", b =>
                {
                    b.HasOne("HouseType", "HouseType")
                        .WithMany("Houses")
                        .HasForeignKey("HouseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HouseType");
                });

            modelBuilder.Entity("QlChoThueNha1.Models.RentalRequest", b =>
                {
                    b.HasOne("QlChoThueNha1.Models.House", "House")
                        .WithMany("RentalRequests")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QlChoThueNha1.Models.User", "User")
                        .WithMany("RentalRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("House");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HouseType", b =>
                {
                    b.Navigation("Houses");
                });

            modelBuilder.Entity("QlChoThueNha1.Models.House", b =>
                {
                    b.Navigation("RentalRequests");
                });

            modelBuilder.Entity("QlChoThueNha1.Models.User", b =>
                {
                    b.Navigation("RentalRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
